// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	tbUserFieldNames          = builder.RawFieldNames(&TbUser{}, true)
	tbUserRows                = strings.Join(tbUserFieldNames, ",")
	tbUserRowsExpectAutoSet   = strings.Join(stringx.Remove(tbUserFieldNames, "create_time", "update_time"), ",")
	tbUserRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(tbUserFieldNames, "id", "create_time", "update_time"))

	cachePublicTbUserIdPrefix = "cache:public:tbUser:id:"
)

type (
	tbUserModel interface {
		Insert(ctx context.Context, data *TbUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TbUser, error)
		Update(ctx context.Context, data *TbUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTbUserModel struct {
		sqlc.CachedConn
		table string
	}

	TbUser struct {
		Id       int64  `db:"id"`
		UserID   int64  `db:"user_ID"`
		Nickname string `db:"nickname"`
	}
)

func newTbUserModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultTbUserModel {
	return &defaultTbUserModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      `"public"."tb_user"`,
	}
}

func (m *defaultTbUserModel) Insert(ctx context.Context, data *TbUser) (sql.Result, error) {
	publicTbUserIdKey := fmt.Sprintf("%s%v", cachePublicTbUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, tbUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.UserID, data.Nickname)
	}, publicTbUserIdKey)
	return ret, err
}

func (m *defaultTbUserModel) FindOne(ctx context.Context, id int64) (*TbUser, error) {
	publicTbUserIdKey := fmt.Sprintf("%s%v", cachePublicTbUserIdPrefix, id)
	var resp TbUser
	err := m.QueryRowCtx(ctx, &resp, publicTbUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tbUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTbUserModel) Update(ctx context.Context, data *TbUser) error {
	publicTbUserIdKey := fmt.Sprintf("%s%v", cachePublicTbUserIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where id = $1", m.table, tbUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Id, data.UserID, data.Nickname)
	}, publicTbUserIdKey)
	return err
}

func (m *defaultTbUserModel) Delete(ctx context.Context, id int64) error {
	publicTbUserIdKey := fmt.Sprintf("%s%v", cachePublicTbUserIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where id = $1", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, publicTbUserIdKey)
	return err
}

func (m *defaultTbUserModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cachePublicTbUserIdPrefix, primary)
}

func (m *defaultTbUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", tbUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTbUserModel) tableName() string {
	return m.table
}
