// Code generated by goctl. DO NOT EDIT.
package com.xhb.logic.http.packet.greet.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.xhb.core.response.HttpResponseData;

public class Response extends HttpResponseData {

	private String message = "";

	public Response() {
	}

	public Response(String message) {
		this.message = message;
	}

	@NotNull 
	public String getMessage() {
		return this.message;
	}

	public void setMessage(@NotNull String message) {
		this.message = message;
	}

}
